Repository linuxfoundation/insights, pull requests merged in 2025-06, with the labels that each got.

#368 feat: decouple tinybird.ts from Nuxt [INS-659]
  frontend/server/data/tinybird/tinybird.test.ts
  frontend/server/data/tinybird/tinybird.ts
Labels: feature

#392 chore: oss launch improvements
  frontend/app/components/modules/explore/components/top-projects.vue
  frontend/app/components/modules/widget/config/contributor/active-organizations/active-organizations.config.ts
  frontend/app/components/modules/widget/config/contributor/contributor-dependency/contributor-dependency.config.ts
  frontend/app/components/modules/widget/config/contributor/contributors-leaderboard/contributors-leaderboard.config.ts
  frontend/app/components/modules/widget/config/contributor/geographical-distribution/geographical-distribution.config.ts
  frontend/app/components/modules/widget/config/contributor/organization-dependency/organization-dependency.config.ts
  frontend/app/components/modules/widget/config/contributor/organizations-leaderboard/organizations-leaderboard.config.ts
  frontend/app/components/modules/widget/config/contributor/retention/retention.config.ts
  frontend/docs/.vitepress/config.ts
  frontend/docs/introduction/contributions/index.md
  frontend/docs/introduction/data-quality/index.md
  frontend/docs/metrics/contributors/index.md
Labels: documentation, feature

#414 Implement search volume nuxt api [INS-661]
  frontend/app/components/modules/widget/config/popularity/search-queries/search-queries.vue
  frontend/app/components/modules/widget/config/widget-area.config.ts
  frontend/server/api/project/[slug]/popularity/search-queries.get.ts
  frontend/server/data/tinybird/package-metrics-data-source.ts
  frontend/server/data/tinybird/requests.types.ts
  frontend/server/data/tinybird/responses.types.ts
  frontend/server/data/tinybird/search-queries-data-source.ts
  frontend/server/data/types.ts
  frontend/server/mocks/tinybird-search-volume-response.mock.ts
  frontend/types/popularity/responses.types.ts
Labels: feature

#428 fix: fix the start and end dates format for the search volume data source
  frontend/server/data/tinybird/search-queries-data-source.ts
Labels: bug
