Repository linuxfoundation/insights, pull requests merged in 2025-09, with the labels that each got.

#612 chore: copilot experimental badge
  frontend/app/components/shared/modules/copilot/components/copilot-sidebar.vue
Labels: feature

#544 chore: update README.md
  README.md
Labels: documentation

#620 fix: fix "includes archived repos" tag being shown when no archived repos are selected
  frontend/app/components/modules/project/components/shared/header.vue
  frontend/app/components/modules/project/store/project.store.ts
  frontend/app/components/modules/project/views/overview.vue
  frontend/app/components/modules/project/views/security.vue
Labels: bug

#632 fix: trust score empty state
  frontend/app/components/modules/project/components/overview/trust-score.vue
  frontend/app/components/modules/project/views/overview.vue
Labels: bug

#634 feat: add missing Gitlab and Gerrit activities in some data sources [IN-686]
  frontend/server/api/project/[slug]/development/pull-requests.get.ts
  frontend/server/data/tinybird/code-review-engagement-data-source.test.ts
  frontend/server/data/tinybird/code-review-engagement-data-source.ts
  frontend/server/data/tinybird/pull-requests-data-source.test.ts
  frontend/server/data/tinybird/pull-requests-data-source.ts
  frontend/server/data/types.ts
  frontend/types/shared/activity-types.ts
Labels: feature

#671 docs: update footer to include blog articles
  frontend/app/config/menu/footer.ts
Labels: documentation

#684 docs: update authored commit definition
  frontend/docs/introduction/contributions/index.md
Labels: documentation
